// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: stakeholders.proto

package stakeholders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMyInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInfoRequest) Reset() {
	*x = GetMyInfoRequest{}
	mi := &file_stakeholders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInfoRequest) ProtoMessage() {}

func (x *GetMyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMyInfoRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_proto_rawDescGZIP(), []int{0}
}

func (x *GetMyInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMyInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInfoResponse) Reset() {
	*x = GetMyInfoResponse{}
	mi := &file_stakeholders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInfoResponse) ProtoMessage() {}

func (x *GetMyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMyInfoResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_proto_rawDescGZIP(), []int{1}
}

func (x *GetMyInfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMyInfoResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetMyInfoResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_stakeholders_proto protoreflect.FileDescriptor

const file_stakeholders_proto_rawDesc = "" +
	"\n" +
	"\x12stakeholders.proto\"+\n" +
	"\x10GetMyInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"S\n" +
	"\x11GetMyInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role2K\n" +
	"\x13StakeholdersService\x124\n" +
	"\tGetMyInfo\x12\x11.GetMyInfoRequest\x1a\x12.GetMyInfoResponse\"\x00B\x14Z\x12proto/stakeholdersb\x06proto3"

var (
	file_stakeholders_proto_rawDescOnce sync.Once
	file_stakeholders_proto_rawDescData []byte
)

func file_stakeholders_proto_rawDescGZIP() []byte {
	file_stakeholders_proto_rawDescOnce.Do(func() {
		file_stakeholders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stakeholders_proto_rawDesc), len(file_stakeholders_proto_rawDesc)))
	})
	return file_stakeholders_proto_rawDescData
}

var file_stakeholders_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stakeholders_proto_goTypes = []any{
	(*GetMyInfoRequest)(nil),  // 0: GetMyInfoRequest
	(*GetMyInfoResponse)(nil), // 1: GetMyInfoResponse
}
var file_stakeholders_proto_depIdxs = []int32{
	0, // 0: StakeholdersService.GetMyInfo:input_type -> GetMyInfoRequest
	1, // 1: StakeholdersService.GetMyInfo:output_type -> GetMyInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stakeholders_proto_init() }
func file_stakeholders_proto_init() {
	if File_stakeholders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stakeholders_proto_rawDesc), len(file_stakeholders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stakeholders_proto_goTypes,
		DependencyIndexes: file_stakeholders_proto_depIdxs,
		MessageInfos:      file_stakeholders_proto_msgTypes,
	}.Build()
	File_stakeholders_proto = out.File
	file_stakeholders_proto_goTypes = nil
	file_stakeholders_proto_depIdxs = nil
}
