// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: proto/tours.proto

package compiled

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TourForCreation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourForCreation) Reset() {
	*x = TourForCreation{}
	mi := &file_proto_tours_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourForCreation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourForCreation) ProtoMessage() {}

func (x *TourForCreation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourForCreation.ProtoReflect.Descriptor instead.
func (*TourForCreation) Descriptor() ([]byte, []int) {
	return file_proto_tours_proto_rawDescGZIP(), []int{0}
}

func (x *TourForCreation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourForCreation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourForCreation) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourForCreation) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type KeypointForCreation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Ordinal       int32                  `protobuf:"varint,6,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeypointForCreation) Reset() {
	*x = KeypointForCreation{}
	mi := &file_proto_tours_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeypointForCreation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeypointForCreation) ProtoMessage() {}

func (x *KeypointForCreation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeypointForCreation.ProtoReflect.Descriptor instead.
func (*KeypointForCreation) Descriptor() ([]byte, []int) {
	return file_proto_tours_proto_rawDescGZIP(), []int{1}
}

func (x *KeypointForCreation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeypointForCreation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeypointForCreation) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *KeypointForCreation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeypointForCreation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeypointForCreation) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *TourForCreation       `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	Keypoints     []*KeypointForCreation `protobuf:"bytes,2,rep,name=keypoints,proto3" json:"keypoints,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_proto_tours_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_proto_tours_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTourRequest) GetTour() *TourForCreation {
	if x != nil {
		return x.Tour
	}
	return nil
}

func (x *CreateTourRequest) GetKeypoints() []*KeypointForCreation {
	if x != nil {
		return x.Keypoints
	}
	return nil
}

func (x *CreateTourRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DistanceAndDuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      float64                `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      float64                `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceAndDuration) Reset() {
	*x = DistanceAndDuration{}
	mi := &file_proto_tours_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceAndDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceAndDuration) ProtoMessage() {}

func (x *DistanceAndDuration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceAndDuration.ProtoReflect.Descriptor instead.
func (*DistanceAndDuration) Descriptor() ([]byte, []int) {
	return file_proto_tours_proto_rawDescGZIP(), []int{3}
}

func (x *DistanceAndDuration) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *DistanceAndDuration) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type TourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int32                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	DrivingStats  *DistanceAndDuration   `protobuf:"bytes,9,opt,name=driving_stats,json=drivingStats,proto3" json:"driving_stats,omitempty"`
	WalkingStats  *DistanceAndDuration   `protobuf:"bytes,10,opt,name=walking_stats,json=walkingStats,proto3" json:"walking_stats,omitempty"`
	CyclingStats  *DistanceAndDuration   `protobuf:"bytes,11,opt,name=cycling_stats,json=cyclingStats,proto3" json:"cycling_stats,omitempty"`
	TimePublished string                 `protobuf:"bytes,12,opt,name=time_published,json=timePublished,proto3" json:"time_published,omitempty"`
	TimeArchived  string                 `protobuf:"bytes,13,opt,name=time_archived,json=timeArchived,proto3" json:"time_archived,omitempty"`
	TimeDrafted   string                 `protobuf:"bytes,14,opt,name=time_drafted,json=timeDrafted,proto3" json:"time_drafted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_proto_tours_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_proto_tours_proto_rawDescGZIP(), []int{4}
}

func (x *TourResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourResponse) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *TourResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourResponse) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TourResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourResponse) GetDrivingStats() *DistanceAndDuration {
	if x != nil {
		return x.DrivingStats
	}
	return nil
}

func (x *TourResponse) GetWalkingStats() *DistanceAndDuration {
	if x != nil {
		return x.WalkingStats
	}
	return nil
}

func (x *TourResponse) GetCyclingStats() *DistanceAndDuration {
	if x != nil {
		return x.CyclingStats
	}
	return nil
}

func (x *TourResponse) GetTimePublished() string {
	if x != nil {
		return x.TimePublished
	}
	return ""
}

func (x *TourResponse) GetTimeArchived() string {
	if x != nil {
		return x.TimeArchived
	}
	return ""
}

func (x *TourResponse) GetTimeDrafted() string {
	if x != nil {
		return x.TimeDrafted
	}
	return ""
}

type GetToursByAuthorIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByAuthorIDRequest) Reset() {
	*x = GetToursByAuthorIDRequest{}
	mi := &file_proto_tours_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByAuthorIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByAuthorIDRequest) ProtoMessage() {}

func (x *GetToursByAuthorIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByAuthorIDRequest.ProtoReflect.Descriptor instead.
func (*GetToursByAuthorIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_tours_proto_rawDescGZIP(), []int{5}
}

func (x *GetToursByAuthorIDRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetToursByAuthorIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*TourResponse        `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByAuthorIDResponse) Reset() {
	*x = GetToursByAuthorIDResponse{}
	mi := &file_proto_tours_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByAuthorIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByAuthorIDResponse) ProtoMessage() {}

func (x *GetToursByAuthorIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByAuthorIDResponse.ProtoReflect.Descriptor instead.
func (*GetToursByAuthorIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_tours_proto_rawDescGZIP(), []int{6}
}

func (x *GetToursByAuthorIDResponse) GetTours() []*TourResponse {
	if x != nil {
		return x.Tours
	}
	return nil
}

type GetTourByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        int32                  `protobuf:"varint,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIDRequest) Reset() {
	*x = GetTourByIDRequest{}
	mi := &file_proto_tours_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIDRequest) ProtoMessage() {}

func (x *GetTourByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_tours_proto_rawDescGZIP(), []int{7}
}

func (x *GetTourByIDRequest) GetTourId() int32 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type SetTourPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        int32                  `protobuf:"varint,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTourPriceRequest) Reset() {
	*x = SetTourPriceRequest{}
	mi := &file_proto_tours_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTourPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTourPriceRequest) ProtoMessage() {}

func (x *SetTourPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTourPriceRequest.ProtoReflect.Descriptor instead.
func (*SetTourPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_tours_proto_rawDescGZIP(), []int{8}
}

func (x *SetTourPriceRequest) GetTourId() int32 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *SetTourPriceRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SetTourPriceRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SetTourPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTourPriceResponse) Reset() {
	*x = SetTourPriceResponse{}
	mi := &file_proto_tours_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTourPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTourPriceResponse) ProtoMessage() {}

func (x *SetTourPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTourPriceResponse.ProtoReflect.Descriptor instead.
func (*SetTourPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_tours_proto_rawDescGZIP(), []int{9}
}

func (x *SetTourPriceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_tours_proto protoreflect.FileDescriptor

const file_proto_tours_proto_rawDesc = "" +
	"\n" +
	"\x11proto/tours.proto\x12\x05tours\"{\n" +
	"\x0fTourForCreation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\xbc\x01\n" +
	"\x13KeypointForCreation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aordinal\x18\x06 \x01(\x05R\aordinal\"\x92\x01\n" +
	"\x11CreateTourRequest\x12*\n" +
	"\x04tour\x18\x01 \x01(\v2\x16.tours.TourForCreationR\x04tour\x128\n" +
	"\tkeypoints\x18\x02 \x03(\v2\x1a.tours.KeypointForCreationR\tkeypoints\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\"M\n" +
	"\x13DistanceAndDuration\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x01R\bduration\"\x85\x04\n" +
	"\fTourResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x05R\bauthorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12?\n" +
	"\rdriving_stats\x18\t \x01(\v2\x1a.tours.DistanceAndDurationR\fdrivingStats\x12?\n" +
	"\rwalking_stats\x18\n" +
	" \x01(\v2\x1a.tours.DistanceAndDurationR\fwalkingStats\x12?\n" +
	"\rcycling_stats\x18\v \x01(\v2\x1a.tours.DistanceAndDurationR\fcyclingStats\x12%\n" +
	"\x0etime_published\x18\f \x01(\tR\rtimePublished\x12#\n" +
	"\rtime_archived\x18\r \x01(\tR\ftimeArchived\x12!\n" +
	"\ftime_drafted\x18\x0e \x01(\tR\vtimeDrafted\"4\n" +
	"\x19GetToursByAuthorIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"G\n" +
	"\x1aGetToursByAuthorIDResponse\x12)\n" +
	"\x05tours\x18\x01 \x03(\v2\x13.tours.TourResponseR\x05tours\"-\n" +
	"\x12GetTourByIDRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\x05R\x06tourId\"]\n" +
	"\x13SetTourPriceRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\x05R\x06tourId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\"0\n" +
	"\x14SetTourPriceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xad\x02\n" +
	"\vTourService\x12;\n" +
	"\n" +
	"CreateTour\x12\x18.tours.CreateTourRequest\x1a\x13.tours.TourResponse\x12Y\n" +
	"\x12GetToursByAuthorID\x12 .tours.GetToursByAuthorIDRequest\x1a!.tours.GetToursByAuthorIDResponse\x12=\n" +
	"\vGetTourByID\x12\x19.tours.GetTourByIDRequest\x1a\x13.tours.TourResponse\x12G\n" +
	"\fSetTourPrice\x12\x1a.tours.SetTourPriceRequest\x1a\x1b.tours.SetTourPriceResponseB\x10Z\x0eproto/compiledb\x06proto3"

var (
	file_proto_tours_proto_rawDescOnce sync.Once
	file_proto_tours_proto_rawDescData []byte
)

func file_proto_tours_proto_rawDescGZIP() []byte {
	file_proto_tours_proto_rawDescOnce.Do(func() {
		file_proto_tours_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tours_proto_rawDesc), len(file_proto_tours_proto_rawDesc)))
	})
	return file_proto_tours_proto_rawDescData
}

var file_proto_tours_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_tours_proto_goTypes = []any{
	(*TourForCreation)(nil),            // 0: tours.TourForCreation
	(*KeypointForCreation)(nil),        // 1: tours.KeypointForCreation
	(*CreateTourRequest)(nil),          // 2: tours.CreateTourRequest
	(*DistanceAndDuration)(nil),        // 3: tours.DistanceAndDuration
	(*TourResponse)(nil),               // 4: tours.TourResponse
	(*GetToursByAuthorIDRequest)(nil),  // 5: tours.GetToursByAuthorIDRequest
	(*GetToursByAuthorIDResponse)(nil), // 6: tours.GetToursByAuthorIDResponse
	(*GetTourByIDRequest)(nil),         // 7: tours.GetTourByIDRequest
	(*SetTourPriceRequest)(nil),        // 8: tours.SetTourPriceRequest
	(*SetTourPriceResponse)(nil),       // 9: tours.SetTourPriceResponse
}
var file_proto_tours_proto_depIdxs = []int32{
	0,  // 0: tours.CreateTourRequest.tour:type_name -> tours.TourForCreation
	1,  // 1: tours.CreateTourRequest.keypoints:type_name -> tours.KeypointForCreation
	3,  // 2: tours.TourResponse.driving_stats:type_name -> tours.DistanceAndDuration
	3,  // 3: tours.TourResponse.walking_stats:type_name -> tours.DistanceAndDuration
	3,  // 4: tours.TourResponse.cycling_stats:type_name -> tours.DistanceAndDuration
	4,  // 5: tours.GetToursByAuthorIDResponse.tours:type_name -> tours.TourResponse
	2,  // 6: tours.TourService.CreateTour:input_type -> tours.CreateTourRequest
	5,  // 7: tours.TourService.GetToursByAuthorID:input_type -> tours.GetToursByAuthorIDRequest
	7,  // 8: tours.TourService.GetTourByID:input_type -> tours.GetTourByIDRequest
	8,  // 9: tours.TourService.SetTourPrice:input_type -> tours.SetTourPriceRequest
	4,  // 10: tours.TourService.CreateTour:output_type -> tours.TourResponse
	6,  // 11: tours.TourService.GetToursByAuthorID:output_type -> tours.GetToursByAuthorIDResponse
	4,  // 12: tours.TourService.GetTourByID:output_type -> tours.TourResponse
	9,  // 13: tours.TourService.SetTourPrice:output_type -> tours.SetTourPriceResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_tours_proto_init() }
func file_proto_tours_proto_init() {
	if File_proto_tours_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tours_proto_rawDesc), len(file_proto_tours_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tours_proto_goTypes,
		DependencyIndexes: file_proto_tours_proto_depIdxs,
		MessageInfos:      file_proto_tours_proto_msgTypes,
	}.Build()
	File_proto_tours_proto = out.File
	file_proto_tours_proto_goTypes = nil
	file_proto_tours_proto_depIdxs = nil
}
